config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Lic:
    repos:
      this_repo:
        commands:
        - licensee detect . --confidence 60 --json
        container: qc.lic_jumpy-cobalt-donkey
timeout: 1800
